### PR TITLE
Webpack 5

### PR DESCRIPTION
**Pull request by Brian-McBride**
Fix for #61 

The real problem is that Webpack 5 isn't exporting most of its typings.
I opened a ticket that addresses this:
https://github.com/webpack/webpack/issues/12869

Until then, I had to define the apply method as `apply(untypedResolver: Resolver | unknown): void` then cast it to this module's `Resolver`.

Once the webpack maintainers export their `Resolver` class definition, then that can be imported and directly replace all the references in this lib and it will work. (I did take the time to test that)

I also added some Jest unit tests. It is probably worth adding the testing to the Husky scripts. During the testing, I found that the `logInfoToStdOut` was not working properly and all logs were going to standard, not error when defined. 

While I was in there, I updated the deps, adjusted the new `chalk` to work, 

I suggest moving from tslint to eslint as the former is depreciated.

### CODE REVIEW

**Comment by Brian-McBride** [comment]
Update: 
I've added the types we really need exposed as a webpack PR. 

https://github.com/webpack/webpack/pull/12875

If it is still open, maybe leave a note there to get it more attention?

**Comment by jonaskello** [comment]
Thanks for the PR! :-) 

I noticed there are some formatting changes in this PR like changing `"` to `'`. This should be handled by prettier and the husky pre-commit hook so everything should be formatted with prettier. I'm not sure why this is not working as intended. Does prettier run when you commit?

**Comment by Brian-McBride** [comment]
Husky is there, but I went ahead and manually ran prettier and pushed back up.

**Comment by jonaskello** [comment]
Released in 3.4.0.

**Pull request merged**
