### PR TITLE
fix: update typing for webpack@^5.94.0

### LINKED ISSUE #109: Type error after upgrading to webpack@5.94.0 (A class can only implement an object type or intersection of object types with statically known members.)
```
export declare class TsconfigPathsPlugin implements ResolvePluginInstance {
    source: string;
    target: string;
    log: Logger.Logger;
    baseUrl?: string | undefined;
    absoluteBaseUrl: string;
    extensions: ReadonlyArray<string>;
    referenceMatchMap: Record<string, TsconfigPaths.MatchPathAsync>;
    matchPath: TsconfigPaths.MatchPathAsync;
    constructor(rawOptions?: Partial<Options.Options>);
    apply(resolver: Resolver): void;
}
```
is failing on `implements ResolvePluginInstance` with error 
```
A class can only implement an object type or intersection of object types with statically known members.ts(2422)
(alias) type ResolvePluginInstance = {
    [index: string]: any;
    apply: (arg0: Resolver) => void;
} | ((this: Resolver, arg1: Resolver) => void)
import ResolvePluginInstance
```

### PR DESCRIPTION
**Pull request by rostislav-simonik**
Fixes #109

### CODE REVIEW

**Comment by rostislav-simonik** [comment]
@jonaskello do you think you could review?

**Review by jonaskello — APPROVED** [review]

**Review by Txabs — APPROVED** [review]

**Comment by Txabs** [comment]
Build failed https://github.com/dividab/tsconfig-paths-webpack-plugin/actions/runs/11630770484/job/32390428277 

`error eslint-plugin-jsdoc@39.9.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.18.0"`

@rostislav-simonik  @jonaskello

**Comment by rostislav-simonik** [comment]
> Gave it a quick test and it seems OK. I guess this should be released as a minor increment?
I haven't tested it on an older Webpack version. it would be good to see if it's backwards compatible. If not, then it's breaking change.

**Comment by rostislav-simonik** [comment]
> Build failed https://github.com/dividab/tsconfig-paths-webpack-plugin/actions/runs/11630770484/job/32390428277
> 
> `error eslint-plugin-jsdoc@39.9.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.18.0"`
> 
> @rostislav-simonik @jonaskello

I can check later today on how to address this issue.

**Comment by rostislav-simonik** [comment]
> > Build failed https://github.com/dividab/tsconfig-paths-webpack-plugin/actions/runs/11630770484/job/32390428277
> > `error eslint-plugin-jsdoc@39.9.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.18.0"`
> > @rostislav-simonik @jonaskello
> 
> I can check later today on how to address this issue.

The issue is unrelated, but I created a PR to address it: https://github.com/dividab/tsconfig-paths-webpack-plugin/pull/111

**Comment by rostislav-simonik** [comment]
@jonaskello minor should be fine. I tested it with the previous version, 5.65.0, and it works.

**Comment by Txabs** [comment]
thank you guys... 

any idea of when this fix will be available publicly in master?

I'm still seeing `4.1.0` as the latest version in https://www.npmjs.com/package/tsconfig-paths-webpack-plugin

(and that's also the version I'm getting when I do a `yarn add -D tsconfig-paths-webpack-plugin`)

**Comment by jonaskello** [comment]
This is now published in 4.2.0

**Pull request merged**
